---
name: "Release"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu
    steps:
      - name: Release
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        id: release
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          github-token: ${{ secrets.GITHUB_TOKEN }}